spring:
  redis:
    url: redis://localhost:6379
  datasource:
    url: jdbc:mysql:///student?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
  application:
    name: scw-project
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
logging:
  file:
    path: ./scw-project/log
server:
  port: 8001

temp:
  profix: "project:create:temp:"