server:
  port: 8003
spring:
  application:
    name: scw-ui
  redis:
    url: redis://localhost:6379
  session:
    store-type: redis
    timeout: 1800
  main:
    allow-bean-definition-overriding: true
  thymeleaf:
    cache: false
logging:
  file:
    path: ./scw-ui/log
  level:
    com:
      deng:
        proj: debug
management:
  endpoints:
    web:
      exposure:
        include: health
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
feign:
  hystrix:
    enabled: true
  client:
    config:
      default:
        connectTimeout: 2000
        readTimeout: 2000
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000